module.exports = {
  apps: [{
    name: 'noonight-api',
    cwd: '/root/noonight/src',
    script: 'dist/main.js',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: 3001,
      REDIS_HOST: 'localhost',
      WORKSPACE_ROOT: '/workspaces',
      STORAGE_ROOT: '/storage',
    },
    env_file: '/root/noonight/.env',
    max_memory_restart: '512M',
    autorestart: true,
    kill_timeout: 10000,
    restart_delay: 5000,
    max_restarts: 10,
    error_file: '/root/noonight/logs/api-error.log',
    out_file: '/root/noonight/logs/api-out.log',
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
  }, {
    name: 'noonight-frontend',
    cwd: '/root/noonight/frontend',
    script: 'node_modules/.bin/next',
    args: 'start -p 3002',
    instances: 1,
    exec_mode: 'fork',
    kill_timeout: 30000,
    env: {
      NODE_ENV: 'production',
      PORT: 3002,
      NEXT_PUBLIC_API_URL: '/api/v1',
    },
    max_memory_restart: '256M',
    autorestart: true,
    restart_delay: 6000,
    max_restarts: 10,
    error_file: '/root/noonight/logs/frontend-error.log',
    out_file: '/root/noonight/logs/frontend-out.log',
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
  }, {
    name: 'whatsapp-bridge',
    cwd: '/root/noonight',
    script: 'bridge.py',
    interpreter: 'python3',
    args: '3456',
    autorestart: true,
    kill_timeout: 10000,
    restart_delay: 5000,
    max_restarts: 10,
  }]
};
